source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Leon0206/MDSpecs.git'

platform :ios, '8.0'

target 'MDIGListKit_Example' do
  
  pod 'IGListKit', '3.4.0'
  
  pod 'MDIGListKit', :path => '../'

end
